Repository GSG-G13/Prayer-Times-RH, pull requests merged in 2023-03, with the labels that each got.

#2 Make AFile > Relates #1
  .gitignore
  package-lock.json
  package.json
  public/css/style.css
  public/index.html
  src/app.js
Labels: approved

#4 make-html-css
  public/css/style.css
  public/images/prayerT.jpg
  public/index.html
Labels: to-review

#8 git data in server
  public/js/main.js
  src/app.js
  src/contollers/error.js
  src/contollers/homePage.js
  src/contollers/index.js
  src/index.js
Labels: approved

#10 showPage
  public/index.html
  src/app.js
  src/contollers/index.js
Labels: to-review

#12 fetch-data
  package-lock.json
  package.json
  public/index.html
  public/js/main.js
  src/contollers/homePage.js
  src/contollers/index.js
Labels: to-review

#19 Edit Ctiy Name
  public/index.html
  public/js/main.js
Labels: approved

#20 readme
  README.md
  public/css/style.css
Labels: to-review

#23 Make test 1 by Raghda
  package-lock.json
  package.json
  src/tests/routes.test.js
Labels: to-review

#24 make-test2-Heba
  src/tests/routes.test.js
Labels: to-review, approved

#26 deploy
  README.md
  src/contollers/error.js
  src/contollers/homePage.js
  src/index.js
Labels: approved
